### ISSUE TITLE
Own3D Plugin won't load

### ISSUE THREAD

**Issue by PassiHD2004** [own3d/own3dpro-obs-plugin#11] opened 2021-01-07 18:49 UTC
So i tried installing the plugin a few times, and it is installed, but its not loading. Its in the right folder.

Here is my last Log: https://obsproject.com/logs/hYu-hO4lDHq_ezbJ

Dont ask why im still using windows 7..... on windows 10 i have 0 performance :+1:

**Comment by ghostzero** [comment] 2021-01-26 09:46
Hey, thanks for your message. Unfortunately, we no longer officially support Windows 7. As Windows 7 is no longer supported by Microsoft since January 14, 2020.

Maybe this link will help you: 
https://github.com/own3d/own3dpro-obs-plugin/wiki/Installation#i-cant-find-own3d-pro-in-tools-menu

Thanks!

**Comment by ghostzero** [comment] 2021-01-26 09:51
This problem is a duplicate of #10. Please follow this issue. I will close this.

**Closed by ghostzero** 2021-01-26 09:51 UTC

**Comment by PassiHD2004** [comment] 2021-01-27 11:46
Is it possible to trick own3d into thinking it’s Windows 10 because I have
to use windows 7 due to performance problems
